### ISSUE TITLE
Failed to get Validation layers on OSX

### ISSUE THREAD

**Issue by manugildev** [unknownue/vulkan-tutorial-rust#34]
MacBook Pro (16-inch, 2019)
CPU: 2.4 GHz 8-Core Intel Core i9
GPU: On a AMD Radeon Pro 5500M 8Gb

Cloned and downloaded assets, tried `cargo run --bin 29` and this happened.

```
No available layers.
thread 'main' panicked at 'Validation layers requested, but not available!', src/utility/share/mod.rs:32:9
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/manuel.gil/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: vulkan_tutorial_rust::utility::share::create_instance
             at ./src/utility/share/mod.rs:32
   2: _29::VulkanApp29::new
             at ./src/tutorials/29_multisampling.rs:106
   3: _29::main
             at ./src/tutorials/29_multisampling.rs:1343
   4: core::ops::function::FnOnce::call_once
             at /Users/manuel.gil/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
MoltenVK vkcubeapp.app runs with no problem :(

**Comment by unknownue** [comment]
Everything is OK on my MacBook. Try to run `vulkaninfo` in Terminal to check if validation layer exists.
You should see something like following:
```
Layers: count = 2
=================
VK_LAYER_KHRONOS_validation (Khronos Validation Layer) Vulkan version 1.2.154, layer version 1:
	Layer Extensions: count = 3
		VK_EXT_debug_report        : extension revision 9
		VK_EXT_debug_utils         : extension revision 1
		VK_EXT_validation_features : extension revision 2
	Devices: count = 2
		GPU id = 0 (AMD Radeon Pro 555X)
		Layer-Device Extensions: count = 3
			VK_EXT_debug_marker     : extension revision 4
			VK_EXT_tooling_info     : extension revision 1
			VK_EXT_validation_cache : extension revision 1

		GPU id = 1 (Intel(R) UHD Graphics 630)
		Layer-Device Extensions: count = 3
			VK_EXT_debug_marker     : extension revision 4
			VK_EXT_tooling_info     : extension revision 1
			VK_EXT_validation_cache : extension revision 1

VK_LAYER_LUNARG_api_dump (LunarG API dump layer) Vulkan version 1.2.154, layer version 2:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id = 0 (AMD Radeon Pro 555X)
		Layer-Device Extensions: count = 1
			VK_EXT_tooling_info : extension revision 1

		GPU id = 1 (Intel(R) UHD Graphics 630)
		Layer-Device Extensions: count = 1
			VK_EXT_tooling_info : extension revision 1
```

**Comment by manugildev** [comment]
Run it as `sudo` made it work.
